management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      enabled: true
      show-details: always

springdoc:
  version: 0.2.0
